const { registerController, verifyOtpController, resendOtpController, loginController, updateProfileController, make_adminController, getAdmin_staff_Lists, getCustomerLists } = require('../../controllers/authcontroller')
const checkRole = require('../../middlewares/checkRole')
const verifyToken = require('../../middlewares/verifyToken')
const multer  = require('multer')
const upload = multer({ dest: 'uploads/' })
const authApi = require('express').Router()
authApi.post('/register',registerController)
authApi.post('/verifyOtp',verifyOtpController)
authApi.post('/login',loginController)
authApi.get('/resendOtp',resendOtpController)
authApi.post('/updateProfile',verifyToken,upload.single('avatar'),updateProfileController)
authApi.patch('/makeAdmin',verifyToken,checkRole(['admin']),make_adminController)
authApi.get('/getAllUsers',verifyToken,checkRole(['admin']),getAdmin_staff_Lists)
authApi.get('/getAllCustomers',verifyToken,checkRole(['admin']),getCustomerLists)

module.exports = authApi